---
title: "Aryballoid shape as a function of applique/burnishing?"
author: "Robert Z. Selden, Jr."
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Elliptical Fourier Analysis

## Load packages + data

```{r load.packages, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# load packages
library(here)
library(wesanderson)
library(Momocs)

# read images
jpg.list <- list.files(here("/jpegs"), full.names = TRUE)

# read attribute data
att.data <- read.csv("att.csv", header = TRUE, as.is = TRUE)

# attribute to factor
att.data$museum <- as.factor(att.data$museum)
att.data$burnish <- as.factor(att.data$burnish)
att.data$applique <- as.factor(att.data$applique)
```

## Generate outlines

```{r outlines + attributes, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# generate outlines
outlines <- jpg.list %>%
  import_jpg()

# add attributes
data.out <- Out(outlines, 
         fac = att.data)

# scale, align, rotate, and center specimens
norm.outlines <- data.out %>% 
  coo_scale() %>%
  coo_align() %>% 
  coo_center()
```

## Pile and mosaics

```{r stack.panel, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# outline pile
pile(norm.outlines)

# mosaic - appliqued or not
mosaic(norm.outlines, ~applique)
# mosaic - burnished or not
mosaic(norm.outlines, ~burnish)
```

## Calibrate harmonic + EFA

```{r cal.harm, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# calibrate how many harmonics needed
calibrate_harmonicpower_efourier(norm.outlines, 
                                 nb.h = 30)

# 10 harmonics needed to capture 99 percent of variation
calibrate_reconstructions_efourier(norm.outlines, 
                                   range = 1:10)

# generate efa outlines with 10 harmonics
efa.outlines <- efourier(norm.outlines, 
                         nb.h = 10, 
                         norm = TRUE)

# use efa.outlines for pca
pca.outlines <- PCA(efa.outlines)
```

## PCA

```{r pca.plot, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# pca 
scree_plot(pca.outlines)

# plot pca by site
plot_PCA(pca.outlines, 
         morphospace_position = "range",
         ~applique, zoom = 0.95)

# plot pca by raw material
plot_PCA(pca.outlines, 
         morphospace_position = "range",
         ~burnish, zoom = 0.95)

# contribution of each pc
# by site
boxplot(pca.outlines, ~applique, nax = 1:5)
# by raw material
boxplot(pca.outlines, ~burnish, nax = 1:5)

# mean shape + 2sd for the first 10 pcs
PCcontrib(pca.outlines, nax = 1:5)
```

## MANOVA + MANOVA_PW

```{r manova, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# manova

# shape difference if appliqued?
MANOVA(pca.outlines, 'applique')

# shape difference if burnished?
MANOVA(pca.outlines, 'burnish')
```

## Mean shapes

```{r ms1, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# mean shapes

# applique
ms.2 <- MSHAPES(efa.outlines, ~applique)
plot_MSHAPES(ms.2, size = 0.75)

# burnish
ms.3 <- MSHAPES(efa.outlines, ~burnish)
plot_MSHAPES(ms.3, size = 0.75)
```
